{
 "title": "Charging Session",
 "tags": [ "internal" ],
 "templating": {
  "list": [
   { "name": "id" },
   { "name": "VIN" },
   {
    "name": "carconnectivity_url",
    "query": {}
   },
   {
    "name": "charging_station_id",
    "query": "SELECT charging_station_uid FROM charging_sessions WHERE charging_sessions.id = $id"
   }
  ]
 },
 "panels": [
  {
   "title": "Battery Level",
   "type": "timeseries",
   "description": "Battery state of charge and range during the charging session.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"first_date\" AS \"time\",\n  \"range\" AS \"Electric Range\",\n  drives.drive_id as \"Drive\"\nFROM drive_ranges\nLEFT JOIN drives ON drive_ranges.drive_id = drives.id\nWHERE\n  drives.vin = '$VIN'\n  AND drives.type = 'ELECTRIC'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nUNION\nSELECT\n  \"last_date\" AS \"time\",\n  \"range\" AS \"Electric Range\",\n  drives.drive_id as \"Drive\"\nFROM drive_ranges\nLEFT JOIN drives ON drive_ranges.drive_id = drives.id\nWHERE\n  drives.vin = '$VIN'\n  AND drives.type = 'ELECTRIC'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nORDER BY \"time\" ASC"
    },
    {
     "alias": "Battery SoC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  \"first_date\" AS \"time\",\n  \"level\" AS \"Level\",\n  drives.drive_id as \"Drive\"\nFROM drive_levels\nLEFT JOIN drives ON drive_levels.drive_id = drives.id\nWHERE\n  drives.vin = '$VIN'\n  AND drives.type = 'ELECTRIC'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nUNION\nSELECT\n  \"last_date\" AS \"time\",\n  \"level\" AS \"Level\",\n  drives.drive_id as \"Drive\"\nFROM drive_levels\nLEFT JOIN drives ON drive_levels.drive_id = drives.id\nWHERE\n  drives.vin = '$VIN'\n  AND drives.type = 'ELECTRIC'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Times",
   "type": "stat",
   "description": "Times of the charging session. Start/End, Plugging/Unplugging, Locking/Unlocking",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "DO $$ \nBEGIN\nIF ${id:singlequote} = 'none' THEN\n  RAISE EXCEPTION 'No id was given, you have to navigate to this dashboard using a link from Charging Sessions dashboard';\nEND IF;\nEND $$;\nSELECT\n  plug_connected_date AS \"Connected\",\n  plug_locked_date AS \"Locked\",\n  session_start_date AS \"Started\",\n  session_end_date AS \"Ended\",\n  plug_unlocked_date AS \"Unlocked\",\n  plug_disconnected_date AS \"Disconnected\"\nFROM charging_sessions\nWHERE\n  id = $id"
    }
   ]
  },
  {
   "title": "Charging",
   "type": "timeseries",
   "description": "Used power and charging rate during the charging session.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "alias": "Charge Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  \"first_date\" AS \"time\",\n  \"power\" AS \"Charging Power\"\nFROM charging_powers \nWHERE\n  vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nUNION\nSELECT\n  \"last_date\" AS \"time\",\n  \"power\" AS \"Charging Power\"\nFROM charging_powers\nWHERE\n  vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nORDER BY \"time\" ASC"
    },
    {
     "alias": "Charge Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  \"first_date\" AS \"time\",\n  \"rate\" AS \"Charging Rate\"\nFROM charging_rates\nWHERE\n  vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nUNION\nSELECT\n  \"last_date\" AS \"time\",\n  \"rate\" AS \"Charging Rate\"\nFROM charging_rates \nWHERE\n  vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nORDER BY \"time\" ASC"
    },
    {
     "dataset": "carconnectivity",
     "rawSql": "SELECT\n  \"first_date\" AS \"time\",\n  \"battery_temperature\" AS \"Battery Temperature\"\nFROM battery_temperatures\nWHERE\n  vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nUNION\nSELECT\n  \"last_date\" AS \"time\",\n  \"battery_temperature\" AS \"Battery Temperature\"\nFROM battery_temperatures\nWHERE\n  vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nORDER BY \"time\" ASC"
    },
    {
     "dataset": "carconnectivity",
     "rawSql": "SELECT\n  \"first_date\" AS \"time\",\n  \"outside_temperature\" AS \"Outside Temperature\"\nFROM outside_temperatures \nWHERE\n  vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nUNION\nSELECT\n  \"last_date\" AS \"time\",\n  \"outside_temperature\" AS \"Outside Temperature\"\nFROM outside_temperatures \nWHERE\n  vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Details",
   "type": "stat",
   "description": "Details of the charging session. The amount is estimated based on the state of charge before and after charging. If you want to work with the real amount and cost in the statistics you can add this data using the edit button.",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "DO $$ \nbegin\nIF ${id:singlequote} = 'none' THEN\n  RAISE EXCEPTION 'No id was given, you have to navigate to this dashboard using a link from Charging Sessions dashboard';\nEND IF;\nEND $$;\nSELECT\n  EXTRACT('epoch' FROM (COALESCE (session_end_date, COALESCE (plug_unlocked_date, plug_disconnected_date)) - COALESCE (session_start_date, COALESCE (plug_locked_date, plug_connected_date)))) AS \"Duration\",\n  (COALESCE(\"real_charged\", COALESCE((\"meter_end_kwh\" - \"meter_start_kwh\"), (\"end_level\" - \"start_level\") * (\n    capacity / 100::NUMERIC)))) / (EXTRACT(epoch FROM (COALESCE(session_end_date, COALESCE(plug_unlocked_date, plug_disconnected_date)) - COALESCE(session_start_date, COALESCE (plug_locked_date, plug_connected_date))))::NUMERIC / 3600::NUMERIC) AS \"Average Charge Power\",\n  charging_type AS \"AC/DC\",\n  \"start_level\" AS \"% Start\",\n  \"end_level\" AS \"% End\",\n  (\"end_level\" - \"start_level\") * (capacity / 100::NUMERIC) AS \"Amount (estimated)\",\n  COALESCE(\"real_charged\", (\"meter_end_kwh\" - \"meter_start_kwh\")) AS \"Amount (real)\",\n  \"real_cost\"::NUMERIC/100::NUMERIC AS \"Cost (real)\",\n  \"session_odometer\" AS \"Odometer\",\n  string_agg(charging_sessions_tags.tags_name, ', ') AS \"Tags\"\nFROM charging_sessions\nLEFT JOIN vehicles ON charging_sessions.vin = vehicles.vin\nLEFT JOIN drives ON vehicles.vin = drives.vin\nLEFT JOIN charging_sessions_tags on charging_sessions.id = charging_sessions_tags.charging_sessions_id\nWHERE\ncharging_sessions.id = ${id}\nGROUP BY session_end_date, plug_unlocked_date, plug_disconnected_date, session_start_date, plug_locked_date, plug_connected_date, \"end_level\", \"start_level\", \"capacity\", charging_type, \"real_charged\", \"meter_end_kwh\", \"meter_start_kwh\", \"real_cost\", \"session_odometer\""
    }
   ]
  },
  {
   "title": "States",
   "type": "state-timeline",
   "description": "Shows the charging state the car was in.",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"first_date\" AS \"time\",\n  \"state\" AS \"Charging\"\nFROM charging_states\nWHERE\n  charging_states.vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nUNION\nSELECT\n  \"last_date\" AS \"time\",\n  \"state\" AS \"Connection\"\nFROM charging_states\nWHERE\n  charging_states.vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Charger",
   "type": "stat",
   "description": "Charger of this charging session. If no data is provided your car might not provide location data. You can still set the location using the edit button.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "DO $$ \nbegin\nIF ${id:singlequote} = 'none' THEN\n  RAISE EXCEPTION 'No id was given, you have to navigate to this dashboard using a link from Charges dashboard';\nEND IF;\nEND $$;\nSELECT\n  charging_stations.name AS \"Name\",\n  charging_stations.address AS \"Address\",\n  charging_stations.max_power AS \"Max Power\",\n  charging_stations.num_spots AS \"Spots\",\n  operator_name AS \"Operator\"\nFROM charging_sessions\nLEFT JOIN charging_stations ON charging_station_uid = charging_stations.uid\nWHERE\n  charging_sessions.id = ${id}"
    }
   ]
  },
  {
   "title": "Charging Location",
   "type": "geomap",
   "description": "Location of the car when charging (green) and the used charger (red). If no location is shown you can add the location data using the edit button.",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(charging_stations.latitude, 'NaN') AS \"Latitude Charger\",\n  COALESCE(charging_stations.longitude, 'NaN') AS \"Longitude Charger\",\n  COALESCE(session_position_latitude, 'NaN') AS \"Latitude Parking\",\n  COALESCE(session_position_longitude, 'NaN') AS \"Longitude Parking\",\n  COALESCE(\"real_charged\", (\"end_level\" - \"start_level\") * capacity / 100::NUMERIC) AS \"Amount Charged\"\nFROM charging_sessions\nLEFT JOIN charging_stations ON charging_sessions.charging_station_uid = charging_stations.uid\nLEFT JOIN vehicles ON charging_sessions.vin = vehicles.vin\nLEFT JOIN drives ON vehicles.vin = drives.vin\nWHERE\n  charging_sessions.id = $id\n  AND drives.type = 'ELECTRIC'"
    }
   ]
  },
  {
   "title": "Location",
   "type": "stat",
   "description": "Charging location of the session. If no data is provided your car might not provide location data. You can still set the location using the edit button.",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "DO $$ \nbegin\nIF ${id:singlequote} = 'none' THEN\n  RAISE EXCEPTION 'No id was given, you have to navigate to this dashboard using a link from Charges dashboard';\nEND IF;\nEND $$;\nSELECT\n  locations.name AS \"Name\",\n  locations.amenity AS \"Amenity\",\n  (locations.road || COALESCE(' '||locations.house_number, '')) AS \"Street\",\n  locations.neighbourhood AS \"Neighbourhood\",\n  locations.postcode AS \"Postcode\",\n  locations.city AS \"City\",\n  locations.state AS \"State\",\n  locations.country AS \"Country\",\n  locations.source AS \"Source\"\nFROM charging_sessions\nLEFT JOIN locations on charging_sessions.location_uid = locations.uid\nWHERE\n  id = $id"
    }
   ]
  }
 ]
}