{
 "title": "Trip Details",
 "tags": [ "internal" ],
 "templating": {
  "list": [
   { "name": "id" },
   { "name": "VIN" },
   {
    "name": "carconnectivity_url",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Battery Level",
   "type": "timeseries",
   "description": "State of charge and electric range during trip. Some cars only provide this data on ignition on/off and not during driving.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"first_date\" AS \"time\",\n  \"level\" AS \"Level\",\n  drives.drive_id as \"Drive\"\nFROM drive_levels\nLEFT JOIN drives ON drive_levels.drive_id = drives.id\nWHERE\n  drives.vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nUNION\nSELECT\n  \"last_date\" AS \"time\",\n  \"level\" AS \"Level\",\n  drives.drive_id as \"Drive\"\nFROM drive_levels\nLEFT JOIN drives ON drive_levels.drive_id = drives.id\nWHERE\n  drives.vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nORDER BY \"time\" ASC"
    },
    {
     "alias": "Battery SoC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"vw-connect.0.$VIN.status.batteryStatus.currentSOC_pct\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "rawSql": "SELECT\n  \"first_date\" AS \"time\",\n  \"range\" AS \"Range\",\n  drives.drive_id as \"Drive\"\nFROM drive_ranges\nLEFT JOIN drives ON drive_ranges.drive_id = drives.id\nWHERE\n  drives.vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nUNION\nSELECT\n  \"last_date\" AS \"time\",\n  \"range\" AS \"Range\",\n  drives.drive_id as \"Drive\"\nFROM drive_ranges\nLEFT JOIN drives ON drive_ranges.drive_id = drives.id\nWHERE\n  drives.vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Details",
   "type": "stat",
   "description": "Details of the tip. On some cars not all data is provided and thus sections may remain empty.",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "CREATE extension IF NOT EXISTS cube;\nCREATE extension IF NOT EXISTS earthdistance;\n\nDO $$ \nBEGIN\nIF ${id:singlequote} = 'none' THEN\n  RAISE EXCEPTION 'No id was given, you have to navigate to this dashboard using a link from Trips dashboard';\nEND IF;\nEND $$;\n\nSELECT\n  \"start_date\" AS \"Start Date\",\n  \"destination_date\" AS \"End Date\",\n  EXTRACT('epoch' FROM(\"destination_date\"-\"start_date\")) AS \"Duration\",\n  (point(start_position_longitude, start_position_latitude)<@>point(destination_position_longitude, destination_position_latitude)) * 1.609344 as \"Distance\",\n  (\"destination_odometer\"-\"start_odometer\") AS \"Length\",\n  \"destination_odometer\" AS \"Odometer\",\n  string_agg(trips_tags.tags_name, ', ') AS \"Tags\"\nFROM trips\nLEFT JOIN trips_tags on trips.id = trips_tags.trips_id\nWHERE\n  id = $id\nGROUP BY \"start_date\", \"destination_date\", start_position_longitude, start_position_latitude, destination_position_longitude, destination_position_latitude, \"destination_odometer\", \"start_odometer\""
    }
   ]
  },
  {
   "title": "Trip",
   "type": "geomap",
   "description": "Trip on map. The car only provides data on ignition on/off and not during driving thus no detailed route can be shown. If the map remains empty your car does not provide location information. You can still add it with edit trip",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "DO $$ \nBEGIN\nIF ${id:singlequote} = 'none' THEN\n  RAISE EXCEPTION 'No id was given, you have to navigate to this dashboard using a link from Trips dashboard';\nEND IF;\nEND $$;\n\nSELECT\n  $__time(\"start_date\"),\n  trips.start_position_latitude AS latitude,\n  trips.start_position_longitude AS longitude \nFROM trips\nWHERE\n  trips.id = $id\nUNION\nSELECT\n  $__time(\"destination_date\"),\n  trips.destination_position_latitude AS latitude,\n  trips.destination_position_longitude AS longitude \nFROM trips\nWHERE\n  trips.id = $id"
    },
    {
     "rawSql": "DO $$ \nBEGIN\nIF ${id:singlequote} = 'none' THEN\n  RAISE EXCEPTION 'No id was given, you have to navigate to this dashboard using a link from Trips dashboard';\nEND IF;\nEND $$;\n\nSELECT\n  $__time(\"destination_date\"),\n  trips.destination_position_latitude AS latitude,\n  trips.destination_position_longitude AS longitude,\n  locations.display_name AS \"Location\"\nFROM trips\nLEFT JOIN locations on trips.destination_location_uid = locations.uid\nWHERE\n  trips.id = $id"
    },
    {
     "rawSql": "DO $$ \nBEGIN\nIF ${id:singlequote} = 'none' THEN\n  RAISE EXCEPTION 'No id was given, you have to navigate to this dashboard using a link from Trips dashboard';\nEND IF;\nEND $$;\n\nSELECT\n  $__time(\"start_date\"),\n  trips.start_position_latitude AS latitude,\n  trips.start_position_longitude AS longitude,\n  locations.display_name AS \"Location\"\nFROM trips\nLEFT JOIN locations on trips.start_location_uid = locations.uid\nWHERE\n  trips.id = $id"
    }
   ]
  },
  {
   "title": "Start Location",
   "type": "stat",
   "description": "Start of the trip. If no data is shown your car does not provide location information. You can still add it with edit trip",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "\nDO $$ \nBEGIN\nIF ${id:singlequote} = 'none' THEN\n  RAISE EXCEPTION 'No id was given, you have to navigate to this dashboard using a link from Trips dashboard';\nEND IF;\nEND $$;\n\nSELECT\n  locations.name AS \"Name\",\n  locations.amenity AS \"Amenity\",\n  (locations.road || COALESCE(' '||locations.house_number, '')) AS \"Street\",\n  locations.neighbourhood AS \"Neighbourhood\",\n  locations.postcode AS \"Postcode\",\n  locations.city AS \"City\",\n  locations.state AS \"State\",\n  locations.country AS \"Country\",\n  locations.source AS \"Source\"\nFROM trips\nLEFT JOIN locations on trips.start_location_uid = locations.uid\nWHERE\n  id = $id"
    }
   ]
  },
  {
   "title": "Destination Location",
   "type": "stat",
   "description": "End of the trip. If no data is shown your car does not provide location information. You can still add it with edit trip",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "DO $$ \nBEGIN\nIF ${id:singlequote} = 'none' THEN\n  RAISE EXCEPTION 'No id was given, you have to navigate to this dashboard using a link from Trips dashboard';\nEND IF;\nEND $$;\n\nSELECT\n  locations.name AS \"Name\",\n  locations.amenity AS \"Amenity\",\n  (locations.road || COALESCE(' '||locations.house_number, '')) AS \"Street\",\n  locations.neighbourhood AS \"Neighbourhood\",\n  locations.postcode AS \"Postcode\",\n  locations.city AS \"City\",\n  locations.state AS \"State\",\n  locations.country AS \"Country\",\n  locations.source AS \"Source\"\nFROM trips\nLEFT JOIN locations on trips.destination_location_uid = locations.uid\nWHERE\n  id = $id"
    }
   ]
  }
 ]
}