{
 "title": "Charging Statistics",
 "tags": [ "carconnectivity" ],
 "time": { "from": "1970-01-01T00:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "VIN",
    "label": "Car",
    "query": "SELECT \"vin\" || ':' || \"name\" || ' (' || \"model\" || ' - ' || \"type\" || ')' FROM vehicles"
   },
   {
    "name": "car_timezone",
    "label": "The Cars timezone",
    "query": "SELECT COALESCE(timezone, 'UTC') FROM vehicles WHERE vin='$VIN'"
   },
   {
    "name": "tag",
    "label": "Show",
    "query": "SELECT tags.name || ': ' || tags.description || '$' || tags.name FROM charging_sessions_tags LEFT JOIN tags ON charging_sessions_tags.tags_name = tags.name"
   },
   {
    "name": "tag_sql",
    "query": "SELECT CASE WHEN LENGTH($$${tag:raw}$$)>0 AND $$${tag:singlequote}$$ != 'all_values' THEN $$ AND charging_sessions_tags.tags_name IN (${tag:singlequote}) $$ ELSE '' END"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Charges",
   "type": "stat",
   "description": "Total number of charging sessions recorded.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(DISTINCT charging_sessions.id) AS \"Number of Charges\"\nFROM charging_sessions\nLEFT JOIN charging_sessions_tags ON charging_sessions.id = charging_sessions_tags.charging_sessions_id\nWHERE\n  ($__timeFilter(\"session_start_date\") OR $__timeFilter(\"session_end_date\")) AND\n  charging_sessions.vin = '$VIN' ${tag_sql:raw}"
    }
   ]
  },
  {
   "title": "Total Cycles",
   "type": "stat",
   "description": "Total number of battery cycles. A charge cycle happens when you use all of the battery’s power—but that doesn’t necessarily mean in a single charge.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(charging_sessions.\"end_level\" - charging_sessions.\"start_level\")/100 AS \"Number of Charges\"\nFROM charging_sessions\nLEFT JOIN charging_sessions_tags ON charging_sessions.id = charging_sessions_tags.charging_sessions_id\nWHERE\n  ($__timeFilter(\"session_start_date\") OR $__timeFilter(\"session_end_date\")) AND\n  charging_sessions.vin = '$VIN' ${tag_sql:raw}"
    }
   ]
  },
  {
   "title": "Charge map",
   "type": "geomap",
   "description": "Charging locations: Size and color corresponds to energy charged at that station.\nLocations are only recorded when provided from the car.\nEnergy is taken from exact value that was added to the charging sessions or estimated based on SoC if no exact data is available.",
   "gridPos": { "h": 20, "w": 13, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"final_latitude\" AS \"Latitude\",\n  \"final_longitude\" AS \"Longitude\",\n  \"Charging Station\",\n  SUM(\"Amount\") AS \"Amount\"\nFROM\n  (SELECT DISTINCT\n  charging_sessions.id,\n  COALESCE(charging_stations.latitude, ROUND(charging_sessions.\"session_position_latitude\"::NUMERIC,3)) AS \"final_latitude\",\n  COALESCE(charging_stations.longitude, ROUND(charging_sessions.\"session_position_longitude\"::NUMERIC,3)) AS \"final_longitude\",\n  COALESCE(charging_stations.name, 'unknown') AS \"Charging Station\",\n  COALESCE(\"real_charged\", COALESCE((\"meter_end_kwh\" - \"meter_start_kwh\"), \n  (\"end_level\" - \"start_level\") * (capacity / 100::NUMERIC))) AS \"Amount\"\nFROM charging_sessions\nLEFT JOIN locations ON charging_sessions.location_uid = locations.uid\nLEFT JOIN vehicles ON charging_sessions.vin = vehicles.vin\nLEFT JOIN charging_stations ON charging_sessions.\"charging_station_uid\" = charging_stations.uid\nLEFT JOIN charging_sessions_tags ON charging_sessions.id = charging_sessions_tags.charging_sessions_id\nLEFT JOIN drives ON vehicles.vin = drives.vin\nWHERE\n  drives.type = 'ELECTRIC' AND\n  COALESCE(charging_stations.latitude, charging_sessions.\"session_position_latitude\") IS NOT NULL AND\n  COALESCE(charging_stations.longitude, charging_sessions.\"session_position_longitude\") IS NOT NULL AND\n  ($__timeFilter(session_start_date) OR $__timeFilter(plug_connected_date) OR $__timeFilter(plug_locked_date)) AND\n  charging_sessions.vin = '$VIN' ${tag_sql:raw}) AS result\nGROUP BY \"final_latitude\", \"final_longitude\", \"Charging Station\""
    }
   ]
  },
  {
   "title": "Total Amount",
   "type": "stat",
   "description": "Total energy charged.\nEnergy is taken from exact value that was added to the charging sessions or estimated based on SoC if no exact data is available.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(\"Amount\") AS \"Amount\"\nFROM\n  (SELECT DISTINCT\n       charging_sessions.id,\n       COALESCE(\"real_charged\", COALESCE((\"meter_end_kwh\"-\"meter_start_kwh\"), \n      (\"end_level\" - \"start_level\") * ( capacity / 100::NUMERIC))) AS \"Amount\"\n    FROM charging_sessions\n    LEFT JOIN vehicles ON charging_sessions.vin = vehicles.vin\n    LEFT JOIN charging_sessions_tags ON charging_sessions.id = charging_sessions_tags.charging_sessions_id\n    LEFT JOIN drives ON vehicles.vin = drives.vin\n    WHERE\n      drives.type = 'ELECTRIC' AND\n      ($__timeFilter(\"session_start_date\") OR $__timeFilter(\"session_end_date\")) AND\n      charging_sessions.vin = '$VIN' ${tag_sql:raw}) AS result"
    }
   ]
  },
  {
   "title": "Total Cost",
   "type": "stat",
   "description": "Sum of all charging costs.\nCharging costs can be added in each charging session.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(\"real_cost\"::NUMERIC/100::NUMERIC) AS \"Cost\"\nFROM\n  (SELECT DISTINCT\n       charging_sessions.id,\n       \"real_cost\"\n    FROM charging_sessions\n    LEFT JOIN vehicles ON charging_sessions.vin = vehicles.vin\n    LEFT JOIN charging_sessions_tags ON charging_sessions.id = charging_sessions_tags.charging_sessions_id\n    WHERE\n      ($__timeFilter(\"session_start_date\") OR $__timeFilter(\"session_end_date\")) AND\n      charging_sessions.vin = '$VIN' ${tag_sql:raw}) AS result"
    }
   ]
  },
  {
   "title": "Difference estimated/real",
   "type": "stat",
   "description": "Difference between estimated energy charged from the car and real energy charged.\nValue is calculated if charging sessions have real energy charged added.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (SUM(\"Estimated\") - SUM(\"Amount\")) / SUM(\"Amount\") * 100 AS \"Delta %\"\nFROM\n  (SELECT DISTINCT\n       charging_sessions.id AS id,\n       ((\"end_level\" - \"start_level\") * (capacity / 100::NUMERIC))::NUMERIC AS \"Estimated\",\n    COALESCE(\"real_charged\", (\"meter_end_kwh\" - \"meter_start_kwh\"))::NUMERIC AS \"Amount\"\n    FROM charging_sessions\n    LEFT JOIN vehicles ON charging_sessions.vin = vehicles.vin\n    LEFT JOIN charging_sessions_tags ON charging_sessions.id = charging_sessions_tags.charging_sessions_id\n    LEFT JOIN drives ON vehicles.vin = drives.vin\n    WHERE\n      drives.type = 'ELECTRIC' AND\n      ($__timeFilter(\"session_start_date\") OR $__timeFilter(\"session_end_date\")) AND\n      (\"real_charged\" IS NOT NULL OR (\"meter_end_kwh\" IS NOT NULL AND \"meter_start_kwh\" IS NOT NULL)) AND \"end_level\" IS NOT NULL AND \"start_level\" IS NOT NULL AND\n      charging_sessions.vin = '$VIN' ${tag_sql:raw}) AS result"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "targets": [
    {
     "dataset": "carconnectivity",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "AC/DC",
   "type": "piechart",
   "description": "Energy added by AC/DC charging sessions.\nAC/DC can be automatically detected if provided from the car. If not it is guessed based on charge power. If the charge power is not available AC/DC can be manually set in the charging sessions.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Type\",\n  SUM(\"Amount\") AS \"Amount\"\nFROM\n  (SELECT DISTINCT\n     charging_sessions.id, \n     COALESCE(charging_type::TEXT, 'unknown') AS \"Type\",\n     COALESCE(\"real_charged\",\n    (\"end_level\" - \"start_level\") * (capacity / 100::NUMERIC)) AS \"Amount\"\n  FROM charging_sessions\n  LEFT JOIN vehicles ON charging_sessions.vin = vehicles.vin\n  LEFT JOIN charging_sessions_tags ON charging_sessions.id = charging_sessions_tags.charging_sessions_id\n  LEFT JOIN drives ON vehicles.vin = drives.vin\n  WHERE\n    drives.type = 'ELECTRIC' AND\n    ($__timeFilter(\"session_start_date\") OR $__timeFilter(\"session_end_date\")) AND\n    charging_sessions.vin = '$VIN' ${tag_sql:raw} AND\n    (\"real_charged\" IS NOT NULL OR \"end_level\" != \"start_level\")) AS result\nGROUP BY \"Type\""
    }
   ]
  },
  {
   "title": "Charging Load",
   "type": "piechart",
   "description": "Amount of  Energy loaded above and below 0.8C.\n1C corresponds to the power necessary to load the car in 1hour to its full capacity.\nGross battery capacity must be set in the vehicles settings.",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH electric_drives AS (\n    SELECT id, vin, COALESCE(capacity_total, capacity) AS capacity_kwh\n    FROM drives\n    WHERE type = 'ELECTRIC' AND vin = '$VIN'\n),\ncharging_ordered AS (\n    SELECT\n        cp.vin,\n        cp.power,\n        cp.first_date,\n        LEAD(cp.first_date) OVER (PARTITION BY cp.vin ORDER BY cp.first_date) AS next_first_date,\n        ed.capacity_kwh\n    FROM charging_powers cp\n    JOIN electric_drives ed ON cp.vin = ed.vin\n    WHERE $__timeFilter(cp.first_date)\n)\nSELECT\n    CASE\n        WHEN power <= capacity_kwh * 0.8 THEN '<=0.8C'\n        ELSE '>0.8C'\n    END AS \"Type\",\n    EXTRACT(EPOCH FROM SUM(\n        COALESCE(next_first_date, first_date + INTERVAL '1 minute') - first_date\n    )) \n    / NULLIF(EXTRACT(EPOCH FROM SUM(SUM(\n        COALESCE(next_first_date, first_date + INTERVAL '1 minute') - first_date\n    )) OVER ()), 0) * 100 AS \"Amount\"\nFROM charging_ordered\nGROUP BY \"Type\"\nORDER BY \"Type\";"
    }
   ]
  },
  {
   "title": "Power distribution",
   "type": "xychart",
   "description": "Distribution of the power used for charging (percentage by time).",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "WITH base AS (\r\n  SELECT\r\n    power,\r\n    (last_date - first_date + INTERVAL '1 minute') AS duration\r\n  FROM charging_powers\r\n  WHERE\r\n    $__timeFilter(first_date)\r\n    AND vin = '$VIN'\r\n),\r\ntotals AS (\r\n  SELECT\r\n    EXTRACT(EPOCH FROM SUM(power * duration)) AS total_energy_seconds,\r\n    SUM(power) AS total_power\r\n  FROM base\r\n),\r\nbuckets AS (\r\n  SELECT\r\n    CASE\r\n      WHEN power < 15 THEN width_bucket(power, -1, 15, 16)\r\n      ELSE width_bucket(power, 15, 205, 19)\r\n    END AS bucket,\r\n    CASE\r\n      WHEN power < 15 THEN\r\n        width_bucket(power, -1, 15, 16)::decimal - 1\r\n      ELSE\r\n        (width_bucket(power, -5, 205, 21)::decimal - 1) * (210.0 / 21)\r\n    END AS center,\r\n    CASE\r\n      WHEN power < 15 THEN\r\n        EXTRACT(EPOCH FROM power * duration)\r\n      ELSE\r\n        power\r\n    END AS weight\r\n  FROM base\r\n)\r\nSELECT\r\n  bucket AS power,\r\n  center AS \"Center of bucket\",\r\n  CASE\r\n    WHEN center < 15 THEN\r\n      (center - 0.5)::text || 'kW to ' || (center + 0.5)::text || 'kW'\r\n    ELSE\r\n      (center - (210.0/42))::text || 'kW to ' || (center + (210.0/42))::text || 'kW'\r\n  END AS \"Bucket\",\r\n  SUM(weight)\r\n    / CASE\r\n        WHEN center < 15 THEN (SELECT total_energy_seconds FROM totals)\r\n        ELSE (SELECT total_power FROM totals)\r\n      END\r\n    * 100 AS \"Proportion\"\r\nFROM buckets\r\nGROUP BY bucket, center\r\nORDER BY center;"
    }
   ]
  },
  {
   "title": "Hourly distribution in timezone $car_timezone",
   "type": "xychart",
   "description": "Distribution of the charging time over the day.\nFor meaningful values wait until a significant number of charging sessions were recorded. Change timezone in vehicle settings.",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "rawSql": "SELECT\n EXTRACT(HOUR FROM ((\"first_date\"::timestamp AT TIME ZONE 'UTC') AT TIME ZONE COALESCE('UTC', 'UTC'))) AS \"Hour\",\n (COUNT(*) / CAST( SUM(COUNT(*)) over () as FLOAT) * 100) AS \"Proportion\",\n ROUND((COUNT(*) / CAST( SUM(COUNT(*)) over () as FLOAT) * 100))::TEXT || '% of charging time' AS \"Text\"\nFROM charging_states\nWHERE\n  $__timeFilter(\"first_date\") AND\n  charging_states.\"state\" = 'CHARGING' AND\n  charging_states.vin = '$VIN'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "DC Charging Speed by SoC",
   "type": "xychart",
   "description": "Charging speeds at different SoC.\nFor meaningful values wait until a significant number of charging sessions were recorded. Only DC charging sessions are considered.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH first_electric_drive AS (\n  SELECT d.id, d.vin\n  FROM drives d\n  WHERE d.type = 'ELECTRIC'\n  ORDER BY d.id\n  LIMIT 1\n)\nSELECT\n  dl.level AS \"SoC [%]\",\n  MIN(cp.power) AS \"Min\",\n  AVG(cp.power) AS \"Avg\",\n  MAX(cp.power) AS \"Max\"\nFROM first_electric_drive fed\nJOIN drive_levels dl\n  ON dl.drive_id = fed.id\nJOIN charging_sessions cs\n  ON cs.vin = fed.vin\n AND cs.charging_type = 'DC'\n AND tstzrange(\n       COALESCE(cs.session_start_date, cs.plug_connected_date),\n       COALESCE(cs.session_end_date, cs.plug_disconnected_date),\n       '[]'\n     )\n     && tstzrange(dl.first_date, dl.last_date, '[]')\nJOIN charging_powers cp\n  ON cp.vin = fed.vin\n AND tstzrange(cp.first_date, cp.last_date, '[]')\n     && tstzrange(dl.first_date, dl.last_date, '[]')\n AND tstzrange(cp.first_date, cp.last_date, '[]')\n     && tstzrange(\n          COALESCE(cs.session_start_date, cs.plug_connected_date),\n          COALESCE(cs.session_end_date, cs.plug_disconnected_date),\n          '[]'\n        )\nGROUP BY\n  dl.level\nORDER BY\n  dl.level;"
    }
   ]
  },
  {
   "title": "Distribution of time remaining in SoC",
   "type": "xychart",
   "description": "Distribution of the time remaining in a specific SoC.\nFor meaningful values wait until a significant number ofvalues were recorded.",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH electric_drive_levels AS (\n  SELECT\n    FLOOR(dl.level / 5) * 5 AS soc_bucket,\n    (dl.last_date - dl.first_date) AS duration\n  FROM drive_levels dl\n  JOIN drives d\n    ON dl.drive_id = d.id\n  WHERE\n    d.type = 'ELECTRIC'\n    AND d.vin = '$VIN'\n    AND $__timeFilter(dl.first_date)\n)\nSELECT\n  soc_bucket AS \"SoC [%]\",\n  EXTRACT(EPOCH FROM SUM(duration)) / EXTRACT(EPOCH FROM SUM(SUM(duration)) OVER ()) * 100 AS \"Proportion\"\nFROM electric_drive_levels\nGROUP BY soc_bucket\nORDER BY soc_bucket;"
    }
   ]
  },
  {
   "title": "DC Charging Speed by Temperature",
   "type": "xychart",
   "description": "Charging speeds at different battery temperature.\nFor meaningful values wait until a significant number of charging sessions were recorded. Only DC charging sessions are considered. Only available for selected cars.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH first_electric_drive AS (\n  SELECT d.id, d.vin\n  FROM drives d\n  WHERE d.type = 'ELECTRIC'\n  ORDER BY d.id\n  LIMIT 1\n)\nSELECT\n  (bt.battery_temperature - 273.15) AS \"Battery Temp [°C]\",\n  MIN(cp.power) AS \"Min\",\n  AVG(cp.power) AS \"Avg\",\n  MAX(cp.power) AS \"Max\"\nFROM first_electric_drive fed\nJOIN drive_levels dl\n  ON dl.drive_id = fed.id\nJOIN charging_sessions cs\n  ON cs.vin = fed.vin\n AND cs.charging_type = 'DC'\n AND tstzrange(\n       COALESCE(cs.session_start_date, cs.plug_connected_date),\n       COALESCE(cs.session_end_date, cs.plug_disconnected_date),\n       '[]'\n     )\n     && tstzrange(dl.first_date, dl.last_date, '[]')\nJOIN charging_powers cp\n  ON cp.vin = fed.vin\n AND tstzrange(cp.first_date, cp.last_date, '[]')\n     && tstzrange(dl.first_date, dl.last_date, '[]')\n AND tstzrange(cp.first_date, cp.last_date, '[]')\n     && tstzrange(\n          COALESCE(cs.session_start_date, cs.plug_connected_date),\n          COALESCE(cs.session_end_date, cs.plug_disconnected_date),\n          '[]'\n        )\nJOIN battery_temperatures bt\n  ON bt.vin = fed.vin\n AND tstzrange(bt.first_date, bt.last_date, '[]')\n     && tstzrange(cp.first_date, cp.last_date, '[]')\nGROUP BY\n  bt.battery_temperature\nORDER BY\n  bt.battery_temperature;\n"
    }
   ]
  }
 ]
}