{
 "title": "Locations",
 "tags": [ "carconnectivity" ],
 "time": { "from": "1970-01-01T00:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "VIN",
    "label": "Car",
    "query": "SELECT \"vin\" || ':' || \"name\" || ' (' || \"model\" || ' - ' || \"type\" || ')' FROM vehicles"
   },
   {
    "name": "carconnectivity_url",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Total Locations",
   "type": "stat",
   "description": "Total different trip locations recorded for the car. If this shows 0 your car does not provide its location. You can still record trips manually.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM\n(\nSELECT DISTINCT\n  UNNEST(ARRAY[\"start_location_uid\",\"destination_location_uid\"]) AS \"location\"\nFROM trips\nWHERE\n  ($__timeFilter(\"start_date\") OR $__timeFilter(\"destination_date\")) AND\n  trips.vin = '$VIN'\n) AS locations\nWHERE \"location\" IS NOT NULL"
    }
   ]
  },
  {
   "title": "Cities",
   "type": "stat",
   "description": "Total different cities visited with the car. If this shows 0 your car does not provide its location. You can still record trips manually.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM\n(\nSELECT DISTINCT\n  UNNEST(ARRAY[\"start_locations\".city,\"destination_locations\".city]) AS \"city\"\nFROM trips\nLEFT JOIN locations start_locations ON trips.start_location_uid = start_locations.uid\nLEFT JOIN locations destination_locations ON trips.destination_location_uid = destination_locations.uid\nWHERE\n  ($__timeFilter(\"start_date\") OR $__timeFilter(\"destination_date\")) AND\n  trips.vin = '$VIN'\n) AS locations\nWHERE \"city\" IS NOT NULL"
    }
   ]
  },
  {
   "title": "States",
   "type": "stat",
   "description": "Total different states visited with the car. If this shows 0 your car does not provide its location. You can still record trips manually.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM\n(\nSELECT DISTINCT\n  UNNEST(ARRAY[\"start_locations\".state,\"destination_locations\".state]) AS \"state\"\nFROM trips\nLEFT JOIN locations start_locations ON trips.start_location_uid = start_locations.uid\nLEFT JOIN locations destination_locations ON trips.destination_location_uid = destination_locations.uid\nWHERE\n  ($__timeFilter(\"destination_date\") OR $__timeFilter(\"destination_date\")) AND\n  trips.vin = '$VIN'\n) AS locations\nWHERE \"state\" IS NOT NULL"
    }
   ]
  },
  {
   "title": "Countries",
   "type": "stat",
   "description": "Total different countries visited with the car. If this shows 0 your car does not provide its location. You can still record trips manually.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM\n(\nSELECT DISTINCT\n  UNNEST(ARRAY[\"start_locations\".country,\"destination_locations\".country]) AS \"country\"\nFROM trips\nLEFT JOIN locations start_locations ON trips.start_location_uid = start_locations.uid\nLEFT JOIN locations destination_locations ON trips.destination_location_uid = destination_locations.uid\nWHERE\n  ($__timeFilter(\"start_date\") OR $__timeFilter(\"destination_date\")) AND\n  trips.vin = '$VIN'\n) AS locations\nWHERE \"country\" IS NOT NULL"
    }
   ]
  },
  {
   "title": "Neighbourhoods",
   "type": "table",
   "description": "Most often visited neighbourhoods visited with the car. If this shows 0 your car does not provide its location. You can still record trips manually.",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"start_locations\".neighbourhood as \"Neighbourhood\",\n  COUNT(*) as \"Visits\"\nFROM trips\nLEFT JOIN locations start_locations ON trips.start_location_uid = start_locations.uid\nWHERE\n \"start_locations\".neighbourhood IS NOT NULL AND\n  ($__timeFilter(\"start_date\") OR $__timeFilter(\"destination_date\")) AND\n  trips.vin = '$VIN'\nGROUP BY \"Neighbourhood\"\nORDER BY \"Visits\" DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Cities",
   "type": "table",
   "description": "Most often visited cities visited with the car. If this shows 0 your car does not provide its location. You can still record trips manually.",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"start_locations\".city as \"City\",\n  COUNT(*) as \"Visits\"\nFROM trips\nLEFT JOIN locations start_locations ON trips.start_location_uid = start_locations.uid\nWHERE\n \"start_locations\".city IS NOT NULL AND\n ($__timeFilter(\"start_date\") OR $__timeFilter(\"destination_date\")) AND\n  trips.vin = '$VIN'\nGROUP BY \"City\"\nORDER BY \"Visits\" DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "States",
   "type": "table",
   "description": "Most often visited states visited with the car. If this shows 0 your car does not provide its location. You can still record trips manually.",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"start_locations\".state as \"State\",\n  COUNT(*) as \"Visits\"\nFROM trips\nLEFT JOIN locations start_locations ON trips.start_location_uid = start_locations.uid\nWHERE\n \"start_locations\".state IS NOT NULL AND\n ($__timeFilter(\"start_date\") OR $__timeFilter(\"destination_date\")) AND\n  trips.vin = '$VIN'\nGROUP BY \"State\"\nORDER BY \"Visits\" DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Last visited",
   "type": "table",
   "description": "20 last visited locations with the car. If this shows 0 your car does not provide its location. You can still record trips manually.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  max(\"destination_date\") AS \"Date\",\n  COALESCE(\"display_name\", CONCAT_WS(', ', COALESCE(CONCAT_WS(', ', name, amenity), nullif(CONCAT_WS(' ', road, house_number), '')), neighbourhood, city, postcode, country)) AS \"Location\"\nFROM trips\nRIGHT JOIN locations ON trips.destination_location_uid = locations.uid\nWHERE\n  $__timeFilter(\"destination_date\") AND\n  trips.vin = '$VIN'\nGROUP BY \"display_name\", \"destination_location_uid\", name, amenity, road, house_number, neighbourhood, city, postcode, country\nORDER BY \"Date\" DESC\nLIMIT 20"
    }
   ]
  }
 ]
}