{
 "title": "Car Overview",
 "tags": [ "carconnectivity" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "VIN",
    "label": "Car",
    "query": "SELECT \"vin\" || ':' || \"name\" || ' (' || \"model\" || ' - ' || \"type\" || ')' FROM vehicles"
   },
   {
    "name": "carconnectivity_url",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "$VIN",
   "type": "gapit-htmlgraphics-panel",
   "description": "Current status of the car ${VIN:text} with VIN ${VIN:raw}. To receive reasonable results you have to make settings for your car.",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "firstNotNull",
      "first",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "/garage/$VIN-car.png.json?fallback=icons/vehicle.png",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Battery (now)",
   "type": "gauge",
   "description": "Current state of charge in percent",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT STRFTIME('%Y-%m-%dT%H:%M:%SZ', first_date) as time, level from drive_levels JOIN drives on drive_levels.id == drives.id WHERE drives.vin==\"$VIN\" AND drives.type = \"ELECTRIC\" ORDER BY first_date DESC LIMIT 1",
     "rawQueryText": "SELECT STRFTIME('%Y-%m-%dT%H:%M:%SZ', first_date) as time, level from drive_levels JOIN drives on drive_levels.id == drives.id WHERE drives.vin==\"$VIN\" AND drives.type = \"ELECTRIC\" ORDER BY first_date DESC LIMIT 1",
     "rawSql": "SELECT\n  \"first_date\" AS \"time\",\n  \"level\" AS \"Battery SoC\"\nFROM drive_levels\nLEFT JOIN drives ON drive_levels.drive_id = drives.id\nWHERE\n  drives.vin = '$VIN'\n  AND drives.type = 'ELECTRIC'\nORDER BY \"time\" DESC\nLIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Levels & Range",
   "type": "timeseries",
   "description": "Battery level and projected range plotted over time for primary and secondary engine. This is useful especially for hybrids.\nSome cars only update these values during startup and shutdown.",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "SELECT STRFTIME('%Y-%m-%dT%H:%M:%SZ', first_date) as time, range as 'Range', drives.drive_id AS label FROM drive_ranges JOIN drives ON drive_ranges.id == drives.id WHERE drives.vin==\"$VIN\"\nUNION\nSELECT STRFTIME('%Y-%m-%dT%H:%M:%SZ', last_date) as time, range as 'Range', drives.drive_id AS label FROM drive_ranges JOIN drives ON drive_ranges.id == drives.id WHERE drives.vin==\"$VIN\"",
     "rawQueryText": "SELECT STRFTIME('%Y-%m-%dT%H:%M:%SZ', first_date) as time, range as 'Range', drives.drive_id AS label FROM drive_ranges JOIN drives ON drive_ranges.id == drives.id WHERE drives.vin==\"$VIN\"\nUNION\nSELECT STRFTIME('%Y-%m-%dT%H:%M:%SZ', last_date) as time, range as 'Range', drives.drive_id AS label FROM drive_ranges JOIN drives ON drive_ranges.id == drives.id WHERE drives.vin==\"$VIN\"",
     "rawSql": "SELECT\n  \"first_date\" AS \"time\",\n  \"range\" AS \"Range\",\n  drives.drive_id as \"Drive\"\nFROM drive_ranges\nLEFT JOIN drives ON drive_ranges.drive_id = drives.id\nWHERE\n  drives.vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nUNION\nSELECT\n  \"last_date\" AS \"time\",\n  \"range\" AS \"Range\",\n  drives.drive_id as \"Drive\"\nFROM drive_ranges\nLEFT JOIN drives ON drive_ranges.drive_id = drives.id\nWHERE\n  drives.vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nORDER BY \"time\" ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT STRFTIME('%Y-%m-%dT%H:%M:%SZ', first_date) as time, range as 'Range', drives.drive_id AS label FROM drive_ranges JOIN drives ON drive_ranges.id == drives.id WHERE drives.vin==\"$VIN\"\nUNION\nSELECT STRFTIME('%Y-%m-%dT%H:%M:%SZ', last_date) as time, range as 'Range', drives.drive_id AS label FROM drive_ranges JOIN drives ON drive_ranges.id == drives.id WHERE drives.vin==\"$VIN\"",
     "rawQueryText": "SELECT STRFTIME('%Y-%m-%dT%H:%M:%SZ', first_date) as time, range as 'Range', drives.drive_id AS label FROM drive_ranges JOIN drives ON drive_ranges.id == drives.id WHERE drives.vin==\"$VIN\"\nUNION\nSELECT STRFTIME('%Y-%m-%dT%H:%M:%SZ', last_date) as time, range as 'Range', drives.drive_id AS label FROM drive_ranges JOIN drives ON drive_ranges.id == drives.id WHERE drives.vin==\"$VIN\"",
     "rawSql": "SELECT\n  \"first_date\" AS \"time\",\n  \"level\" AS \"Level\",\n  drives.drive_id as \"Drive\"\nFROM drive_levels\nLEFT JOIN drives ON drive_levels.drive_id = drives.id\nWHERE\n  drives.vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nUNION\nSELECT\n  \"last_date\" AS \"time\",\n  \"level\" AS \"Level\",\n  drives.drive_id as \"Drive\"\nFROM drive_levels\nLEFT JOIN drives ON drive_levels.drive_id = drives.id\nWHERE\n  drives.vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nORDER BY \"time\" ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT STRFTIME('%Y-%m-%dT%H:%M:%SZ', first_date) as time, range as 'Range', drives.drive_id AS label FROM drive_ranges JOIN drives ON drive_ranges.id == drives.id WHERE drives.vin==\"$VIN\"\nUNION\nSELECT STRFTIME('%Y-%m-%dT%H:%M:%SZ', last_date) as time, range as 'Range', drives.drive_id AS label FROM drive_ranges JOIN drives ON drive_ranges.id == drives.id WHERE drives.vin==\"$VIN\"",
     "rawQueryText": "SELECT STRFTIME('%Y-%m-%dT%H:%M:%SZ', first_date) as time, range as 'Range', drives.drive_id AS label FROM drive_ranges JOIN drives ON drive_ranges.id == drives.id WHERE drives.vin==\"$VIN\"\nUNION\nSELECT STRFTIME('%Y-%m-%dT%H:%M:%SZ', last_date) as time, range as 'Range', drives.drive_id AS label FROM drive_ranges JOIN drives ON drive_ranges.id == drives.id WHERE drives.vin==\"$VIN\"",
     "rawSql": "SELECT\n  \"first_date\" AS \"time\",\n  \"outside_temperature\" AS \"Outside Temperature\"\nFROM outside_temperatures \nWHERE\n  vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nUNION\nSELECT\n  \"last_date\" AS \"time\",\n  \"outside_temperature\" AS \"Outside Temperature\"\nFROM outside_temperatures \nWHERE\n  vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nORDER BY \"time\" ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT STRFTIME('%Y-%m-%dT%H:%M:%SZ', first_date) as time, range as 'Range', drives.drive_id AS label FROM drive_ranges JOIN drives ON drive_ranges.id == drives.id WHERE drives.vin==\"$VIN\"\nUNION\nSELECT STRFTIME('%Y-%m-%dT%H:%M:%SZ', last_date) as time, range as 'Range', drives.drive_id AS label FROM drive_ranges JOIN drives ON drive_ranges.id == drives.id WHERE drives.vin==\"$VIN\"",
     "rawQueryText": "SELECT STRFTIME('%Y-%m-%dT%H:%M:%SZ', first_date) as time, range as 'Range', drives.drive_id AS label FROM drive_ranges JOIN drives ON drive_ranges.id == drives.id WHERE drives.vin==\"$VIN\"\nUNION\nSELECT STRFTIME('%Y-%m-%dT%H:%M:%SZ', last_date) as time, range as 'Range', drives.drive_id AS label FROM drive_ranges JOIN drives ON drive_ranges.id == drives.id WHERE drives.vin==\"$VIN\"",
     "rawSql": "SELECT\n  \"first_date\" AS \"time\",\n  \"battery_temperature\" AS \"Battery Temperature\"\nFROM battery_temperatures \nWHERE\n  vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nUNION\nSELECT\n  \"last_date\" AS \"time\",\n  \"battery_temperature\" AS \"Battery Temperature\"\nFROM battery_temperatures \nWHERE\n  vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nORDER BY \"time\" ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Car Online State",
   "type": "stat",
   "description": "Indicates if the car is currently awake (online) or sleeping.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Car is online",
     "rawSql": "SELECT \"last_date\" AS \"time\", connection_state FROM connection_states WHERE vin = '$VIN' ORDER BY first_date DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Last Data from Car",
   "type": "stat",
   "description": "Time when the last successful connection to the servers were made and time when the last information from the car was received.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Last connection",
     "rawSql": "SELECT \"last_date\" AS \"Last update\" FROM charging_powers WHERE vin = '$VIN'\nUNION\nSELECT \"last_date\" AS \"Last update\" FROM charging_rates WHERE vin = '$VIN'\nUNION\nSELECT \"last_date\" AS \"Last update\" FROM charging_states WHERE vin = '$VIN'\nUNION\nSELECT \"last_date\" AS \"Last update\" FROM climatization_states WHERE vin = '$VIN'\nUNION\nSELECT \"last_date\" AS \"Last update\" FROM connection_states WHERE vin = '$VIN'\nUNION\nSELECT \"last_date\" AS \"Last update\" FROM drive_levels LEFT JOIN drives ON drive_levels.drive_id = drives.id WHERE vin = '$VIN'\nUNION\nSELECT \"last_date\" AS \"Last update\" FROM drive_ranges LEFT JOIN drives ON drive_ranges.drive_id = drives.id WHERE vin = '$VIN'\nUNION\nSELECT \"last_date\" AS \"Last update\" FROM outside_temperatures WHERE vin = '$VIN'\nUNION\nSELECT \"last_date\" AS \"Last update\" FROM states WHERE vin = '$VIN'\nORDER BY \"Last update\" DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Projected Electric Range (now)",
   "type": "gauge",
   "description": "Current range calculated from current consumption",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "queryText": "SELECT STRFTIME('%Y-%m-%dT%H:%M:%SZ', first_date) as time, range from drive_ranges JOIN drives on drive_ranges.id == drives.id WHERE drives.vin==\"$VIN\" AND drives.type = \"ELECTRIC\" ORDER BY first_date DESC LIMIT 1",
     "rawQueryText": "SELECT STRFTIME('%Y-%m-%dT%H:%M:%SZ', first_date) as time, range from drive_ranges JOIN drives on drive_ranges.id == drives.id WHERE drives.vin==\"$VIN\" AND drives.type = \"ELECTRIC\" ORDER BY first_date DESC LIMIT 1",
     "rawSql": "SELECT\n  \"first_date\" AS \"time\",\n  \"range\" AS \"Electric Range\"\nFROM drive_ranges\nLEFT JOIN drives ON drive_ranges.drive_id = drives.id\nWHERE\n  drives.vin = '$VIN'\n  AND drives.type = 'ELECTRIC'\nORDER BY \"time\" DESC\nLIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Charging Power (now)",
   "type": "gauge",
   "description": "If the car is charging, current charging power. This value is not available on all cars.",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"first_date\" AS \"time\",\n  \"power\" AS \"Power\"\nFROM charging_powers\nWHERE\n  vin = '$VIN'\nORDER BY \"time\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Consumption & Range extrapolated to 100% SoC",
   "type": "timeseries",
   "description": "Current consumption and Range if the car would be at 100% SoC. Consumption is calculated as capacity divided by current range. The green area shows the WLTP range.\nSome cars only update these values during startup and shutdown. Value is only useful for electric cars or hybrids running on electricity only.",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "targets": [
    {
     "alias": "Extrapolated range at 100% SoC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  \"first_date\" AS \"time\",\n  \"range_estimated_full\" AS \"Range at 100%\",\n  drives.drive_id as \"Drive\"\nFROM drive_ranges_estimated_full\nLEFT JOIN drives ON drive_ranges_estimated_full.drive_id = drives.id\nWHERE\n  drives.vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nUNION\nSELECT\n  \"last_date\" AS \"time\",\n  \"range_estimated_full\" AS \"Range at 100%\",\n  drives.drive_id as \"Drive\"\nFROM drive_ranges_estimated_full\nLEFT JOIN drives ON drive_ranges_estimated_full.drive_id = drives.id\nWHERE\n  drives.vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nORDER BY \"time\" ASC"
    },
    {
     "alias": "Extrapolated range at 100% SoC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  \"first_date\" AS \"time\",\n  \"consumption\" AS \"Electric Consumption\",\n  drives.drive_id as \"Drive\"\nFROM drive_consumptions \nLEFT JOIN drives ON drive_consumptions.drive_id = drives.id\nWHERE\n  drives.vin = '$VIN'\n  AND drives.type = 'ELECTRIC'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nUNION\nSELECT\n  \"last_date\" AS \"time\",\n  \"consumption\" AS \"Electric Consumption\",\n  drives.drive_id as \"Drive\"\nFROM drive_consumptions\nLEFT JOIN drives ON drive_consumptions.drive_id = drives.id\nWHERE\n  drives.vin = '$VIN'\n  AND drives.type = 'ELECTRIC'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nORDER BY \"time\" ASC"
    },
    {
     "alias": "Extrapolated range at 100% SoC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  \"first_date\" AS \"time\",\n  \"consumption\" AS \"Fuel Consumption\",\n  drives.drive_id as \"Drive\"\nFROM drive_consumptions \nLEFT JOIN drives ON drive_consumptions.drive_id = drives.id\nWHERE\n  drives.vin = '$VIN'\n  AND drives.type IN ('FUEL', 'GASOLINE', 'PETROL', 'DIESEL', 'CNG', 'LPG')\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nUNION\nSELECT\n  \"last_date\" AS \"time\",\n  \"consumption\" AS \"Fuel Consumption\",\n  drives.drive_id as \"Drive\"\nFROM drive_consumptions\nLEFT JOIN drives ON drive_consumptions.drive_id = drives.id\nWHERE\n  drives.vin = '$VIN'\n  AND drives.type IN ('FUEL', 'GASOLINE', 'PETROL', 'DIESEL', 'CNG', 'LPG')\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nORDER BY \"time\" ASC"
    },
    {
     "alias": "Extrapolated range at 100% SoC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  unnest(ARRAY[to_timestamp(${__from}/1000), to_timestamp(${__to}/1000)]) AS time,\n  wltp_range as \"WLTP\",\n  drive_id as \"Drive\"\nFROM\n  drives\nWHERE\n  drives.vin = '$VIN'\n  AND wltp_range IS NOT NULL\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Information",
   "type": "gapit-htmlgraphics-panel",
   "description": "Shows information for the usage of VWsFriend",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  drives.*,\n  vehicles.name,\n  vehicles.type AS vehicle_type\nFROM drives\nLEFT JOIN vehicles ON drives.vin = vehicles.vin\nWHERE\n  vehicles.vin = '${VIN}'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  logtime,\n  log FROM\n(\n  (SELECT\n    session_start_date AS logtime,\n    'charging started' AS log\n  FROM charging_sessions\n  WHERE session_start_date IS NOT NULL AND vin = '${VIN}'\n  ORDER BY session_start_date DESC\n  LIMIT 3)\n  UNION\n  (SELECT\n    plug_connected_date AS logtime,\n    'charging cable connected' AS log\n  FROM charging_sessions\n  WHERE plug_connected_date IS NOT NULL AND vin = '${VIN}'\n  ORDER BY plug_connected_date DESC\n  LIMIT 3)\n  UNION\n  (SELECT\n    plug_locked_date AS logtime,\n    'charging connector locked' AS log\n  FROM charging_sessions\n  WHERE plug_locked_date IS NOT NULL AND vin = '${VIN}'\n  ORDER BY plug_locked_date DESC\n  LIMIT 3)\n  UNION\n    (SELECT\n    session_end_date AS logtime,\n    'charging ended' AS log\n  FROM charging_sessions\n  WHERE session_end_date IS NOT NULL AND vin = '${VIN}'\n  ORDER BY session_end_date DESC\n  LIMIT 3)\n  UNION\n  (SELECT\n    plug_disconnected_date AS logtime,\n    'charging cable disconnected' AS log\n  FROM charging_sessions\n  WHERE plug_disconnected_date IS NOT NULL AND vin = '${VIN}'\n  ORDER BY plug_disconnected_date DESC\n  LIMIT 3)\n  UNION\n  (SELECT\n    plug_unlocked_date AS logtime,\n    'charging connector unlocked' AS log\n  FROM charging_sessions\n  WHERE plug_unlocked_date IS NOT NULL AND vin = '${VIN}'\n  ORDER BY plug_unlocked_date DESC\n  LIMIT 3)\n   UNION\n  (SELECT\n    \"start_date\" AS logtime,\n    'trip started' AS log\n  FROM trips\n  WHERE \"start_date\" IS NOT NULL AND vin = '${VIN}'\n  ORDER BY \"start_date\" DESC\n  LIMIT 10)\n  UNION\n  (SELECT\n    \"destination_date\" AS logtime,\n    'trip ended' AS log\n  FROM trips\n  WHERE \"destination_date\" IS NOT NULL AND vin = '${VIN}'\n  ORDER BY \"destination_date\" DESC\n  LIMIT 10)\n  UNION\n  (SELECT\n  \"first_date\" AS logtime,\n  CASE WHEN \"state\"= 'OFF' THEN 'climatisation stopped'\n       WHEN \"state\"= 'HEATING' THEN 'climatisation heating'\n       WHEN \"state\"= 'COOLING' THEN 'climatisation cooling'\n       WHEN \"state\"= 'VENTILATION' THEN 'climatisation ventilating'\n       ELSE 'unkown'\n  END AS log\n  FROM climatization_states\n  WHERE \"first_date\" IS NOT NULL AND vin = '${VIN}'\n  ORDER BY \"first_date\" DESC\n  LIMIT 10)\n  UNION\n  (SELECT\n    session_date AS logtime,\n    'car was refueled' AS log\n  FROM refuel_sessions\n  WHERE session_date IS NOT NULL AND vin = '${VIN}'\n  ORDER BY session_date DESC\n  LIMIT 3)\n) AS logs\nORDER BY 1 DESC\nLIMIT 20"
    }
   ]
  },
  {
   "title": "Efficiency",
   "type": "timeseries",
   "description": "Current efficiency. 100% means that with the current consumption the WLTP range is reached.\nSome cars only update these values during startup and shutdown. Value is only useful for electric cars or hybrids running on electricity only.",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Efficiency (Compared to WLTP range)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  \"first_date\" AS \"time\",\n  \"range_estimated_full\"/\"wltp_range\"*100 AS \"Efficiency\",\n  drives.drive_id as \"Drive\"\nFROM drive_ranges_estimated_full\nLEFT JOIN drives ON drive_ranges_estimated_full.drive_id = drives.id\nWHERE\n  drives.vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\n  AND wltp_range IS NOT NULL\nUNION\nSELECT\n  \"last_date\" AS \"time\",\n  \"range_estimated_full\"/\"wltp_range\"*100 AS \"Efficiency\",\n  drives.drive_id as \"Drive\"\nFROM drive_ranges_estimated_full\nLEFT JOIN drives ON drive_ranges_estimated_full.drive_id = drives.id\nWHERE\n  drives.vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\n  AND wltp_range IS NOT NULL\nORDER BY \"time\" ASC"
    },
    {
     "alias": "Efficiency (Compared to WLTP range)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  unnest(ARRAY[to_timestamp(${__from}/1000), to_timestamp(${__to}/1000)]) AS time,\n  100 AS \"100% = WLTP Range\"\nFROM\n  drives\nWHERE\n  drives.vin = '$VIN'\n  AND wltp_range IS NOT NULL\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Charging",
   "type": "timeseries",
   "description": "Charging power and charging rate in kilometers over time.",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "alias": "Charge Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "rawSql": "SELECT\r\n  \"first_date\" AS \"time\",\r\n  \"power\" AS \"Charging Power\"\r\nFROM charging_powers \r\nWHERE\r\n  vin = '$VIN'\r\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\r\nUNION\r\nSELECT\r\n  \"last_date\" AS \"time\",\r\n  \"power\" AS \"Charging Power\"\r\nFROM charging_powers\r\nWHERE\r\n  vin = '$VIN'\r\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\r\nORDER BY \"time\" ASC"
    },
    {
     "alias": "Charge Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "rawSql": "SELECT\r\n  \"first_date\" AS \"time\",\r\n  \"rate\" AS \"Charging Rate\"\r\nFROM charging_rates\r\nWHERE\r\n  vin = '$VIN'\r\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\r\nUNION\r\nSELECT\r\n  \"last_date\" AS \"time\",\r\n  \"rate\" AS \"Charging Rate\"\r\nFROM charging_rates \r\nWHERE\r\n  vin = '$VIN'\r\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\r\nORDER BY \"time\" ASC"
    },
    {
     "alias": "Charge Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "rawSql": "SELECT\r\n  \"first_date\" AS \"time\",\r\n  \"outside_temperature\" AS \"Outside Temperature\"\r\nFROM outside_temperatures \r\nWHERE\r\n  vin = '$VIN'\r\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\r\nUNION\r\nSELECT\r\n  \"last_date\" AS \"time\",\r\n  \"outside_temperature\" AS \"Outside Temperature\"\r\nFROM outside_temperatures \r\nWHERE\r\n  vin = '$VIN'\r\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\r\nORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Version",
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 24 },
   "options": {
    "content": "CarConnectivity Grafana version: [0.0.0dev](https://github.com/tillsteinbach/CarConnectivity-grafana/)"
   }
  },
  {
   "title": "States",
   "type": "state-timeline",
   "description": "Highlights the times when the car is online, heating and charging.",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Car state",
     "rawSql": "SELECT\n  \"first_date\" AS \"time\",\n  \"state\" AS \"Vehicle State\"\nFROM states\nWHERE\n  states.vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nUNION\nSELECT\n  \"last_date\" AS \"time\",\n  \"state\" AS \"Vehicle State\"\nFROM states\nWHERE\n  states.vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nORDER BY \"time\" ASC"
    },
    {
     "alias": "Car state",
     "rawSql": "SELECT\n  \"first_date\" AS \"time\",\n  \"connection_state\" AS \"Connection\"\nFROM connection_states\nWHERE\n  connection_states.vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nUNION\nSELECT\n  \"last_date\" AS \"time\",\n  \"connection_state\" AS \"Connection\"\nFROM connection_states\nWHERE\n  connection_states.vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nORDER BY \"time\" ASC"
    },
    {
     "dataset": "carconnectivity",
     "rawSql": "SELECT\n  \"first_date\" AS \"time\",\n  \"state\" AS \"Charging\"\nFROM charging_states\nWHERE\n  charging_states.vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nUNION\nSELECT\n  \"last_date\" AS \"time\",\n  \"state\" AS \"Connection\"\nFROM charging_states\nWHERE\n  charging_states.vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nORDER BY \"time\" ASC"
    },
    {
     "dataset": "carconnectivity",
     "rawSql": "SELECT\n  \"first_date\" AS \"time\",\n  \"state\" AS \"Climatizaton\"\nFROM climatization_states\nWHERE\n  climatization_states.vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nUNION\nSELECT\n  \"last_date\" AS \"time\",\n  \"state\" AS \"Climatizaton\"\nFROM climatization_states\nWHERE\n  climatization_states.vin = '$VIN'\n  AND ($__timeFilter(\"first_date\") OR $__timeFilter(\"last_date\"))\nORDER BY \"time\" ASC"
    }
   ]
  }
 ]
}