# config file version
apiVersion: 1

deleteDatasources:
  - name: CarConnectivity-ENV-json
    orgId: 1

datasources:
  - name: CarConnectivity-ENV-json
    orgId: 1
    uid: CarConnectivity-Env-json-provisioned
    type: yesoreyeram-infinity-datasource
    isDefault: false
    editable: false
    jsonData:
      refData:
        - name: env
          data: '[{"carconnectivity_ui_url":"$CARCONNECTIVITY_UI_URL"}]'
